Ansible 2
Otus-DevOps-2023-01/DenisV003_infra pull request #8
Opened 2023-04-05 15:44 UTC by DenisV003

# Выполнено ДЗ №

 - [ *] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Выполнены все пункты

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ *] Выставил label с номером домашнего задания
 - [ *] Выставил label с темой домашнего задания

2023-04-05 15:48 UTC, DenisV003 commented
Добрый день. В автотесте почему то ругается на неизвестный ключ при validate packer. Хотя при запуске этих же команд на своей машине ошибок нет. 
dvoloshchik@voronezhoffice15  ~/Otus/VS/DenisV003_infra   ansible-2 ±  packer validate -var-file=packer/variables.json.example packer/db.json
The configuration is valid.

2023-04-06 08:12 UTC, mrgreyves requested changes
Здравствуйте!)
Все верно
Было бы странно если на раннерах были ваши ключи /home/dvoloshchik/Otus/key.json
Добавьте фейковый ключ для пакера и в конфиге укажите пути для него

2023-04-06 09:51 UTC, DenisV003 commented
Это и есть фейковый ключ, который лежит в папке: /home/dvoloshchik/Otus/key.json. Ранее его же и использовал для выполнения ДЗ по packer, и автотесты приходили. Ниже добавил скриншот и содержимое. Пробовал другие пути, полный путь и через ./key.json. 
{
  "id": "ajevce7emn08l9c8nc76",
  "service_account_id": "ajevpu4ev0sv0jfqsdd8",
  "created_at": "2023-03-09T15:10:06.417174522Z",
  "key_algorithm": "RSA_2048",
  "public_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0B\n-----END PUBLIC KEY-----\n",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhki\n-----END PRIVATE KEY-----\n"
}
![image](https://user-images.githubusercontent.com/125120824/230341647-f3a27cfc-3b65-4033-a917-365c4cba5122.png)

2023-04-06 09:58 UTC, DenisV003 commented
Исправлено

2023-04-08 19:10 UTC, mrgreyves approved these changes
Здравствуйте!!)
Вот теперь все корректно =)

2023-04-10 06:07 UTC, merged